spring:
  profiles:
      active: prod
  application:
    name: BetaBuilders


  #JPA
  jpa:
    show-sql: true

  #Spring Datasource Connection Pooling configuration
  datasource:
    username: root
    password: # Remove it, if you are using XAMPP (Windows)
    url: jdbc:mysql://localhost:3306/betabuilders?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      validation-query: SELECT 1
      max-active: 5
      max-idle: 3
      max-wait: 8000

  #Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:mysql://localhost:3306?useSSL=false
    schemas: betabuilders
    user: root
    password: # Remove it, if you are using XAMPP (Windows)

logging:
  level:
    org:
      springframework:
        security: DEBUG
